# Generated by Django 4.0.5 on 2022-06-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year_released',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
